### ISSUE TITLE
new macOS install needs manual permissions for QR permissions

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#129]
The app does not prompt users for camera permissions when QR scanner is initialized, instead, the app just crashes.

**Comment by cculianu** [comment]
I think this is 90% fixed in recent commits after this issue report has been filed.  If you do mess with the settings in the privacy pane later, you reported it crashes.. but by default it works.  At least I couldn't get it to crash here on 2 machines (Mojave and Catalina).

Let me know if it's still the case.
