### ISSUE TITLE
Network Token/PO tabs rows don't remain selected

### ISSUE THREAD

**Issue by jcramer** [simpleledger/Electron-Cash-SLP#179]
Reproduce:

Go to network dialog tokens tab, click on a row and see they don't remain highlighted.

**Comment by EchterAgo** [comment]
This is caused by this:

https://github.com/simpleledger/Electron-Cash-SLP/commit/eabceef94f63bcbffad0d02af89e54d2d2f7f7df#diff-9fe7c95cd8ed4ac5b136812545a681a41b22364d249f0182e5296e5355a17224R77

This made the network dialog unconditionally update every 500 milliseconds. The `SlpGsServeListWidget` needs to preserve its selection in the `update` function. Same for the `PostOfficeServeListWidget`.

**Comment by jcramer** [comment]
This same fix needs to be applied to the post office tab, @OPReturnCode
